version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
  build:
    commands:
      - echo Build started on `date`
      - echo Installing Serverless framework...
      - npm install -g serverless@3.39.0
      - npm install
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Deploying with Serverless framework...
      - serverless deploy --region $AWS_DEFAULT_REGION
      - echo Deployment completed on `date`